apiVersion: v1
kind: Pod
metadata:
  name: console-gql
  labels:
    app: console-gql
  namespace: rawagner
spec:
  containers:
    - name: console-gql
      image: quay.io/rawagner/console-gql
      ports:
        - containerPort: 4000
        - containerPort: 8080
      env:
        - name: k8sTOKEN
          value: zNHfuATHCY52oHhxbQs7sDVuWQ75kRKXLpeu3XC0Asc
      resources:
        requests:
          cpu: 1000m
          memory: 1Gi



apiVersion: v1
kind: Service
metadata:
  name: console-gql
  namespace: rawagner
spec:
  selector:
    app: console-gql
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000



